spring:
  application:
    name: hrbank

  # DataSource (Railway ENV 기반)
  datasource:
    url: ${JDBC_DATABASE_URL}
    driver-class-name: org.postgresql.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update                       # 배포 시 엔티티 기준 테이블 자동 생성
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        jdbc.time_zone: UTC
    open-in-view: false

  # Batch 초기화 스크립트 생략
  batch:
    jdbc:
      initialize-schema: never

# 로깅
logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: WARN

# HRBank 커스텀 설정
hrbank:
  storage:
    type: local
    local:
      root-path: ./storage
  backup:
    cron: "0 0 * * * *"
    worker: "system"

# Batch 파일 경로
batch:
  file:
    output-path: /backup/output/employee_data.csv
