spring:
  application:
    name: hrbank

  # DataSource (Railway ENV 기반)
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update                       # 배포 시 엔티티 기준 테이블 자동 생성
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        jdbc.time_zone: UTC
    open-in-view: false

# application-prod.yml
swagger:
  server-url: https://hrbank-production.up.railway.app/

hrbank:
  storage:
    type: local
    local:
      root-path: /storage
